# Generated by Django 2.1.7 on 2019-02-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_made', models.DateField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Time Start')),
                ('time_end', models.TimeField(verbose_name='Time End')),
                ('plan_title', models.CharField(max_length=20)),
                ('plan_description', models.TextField(max_length=300)),
                ('plan_tag', models.CharField(choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Social', 'Social'), ('Occupational', 'Occupational'), ('Intellectual', 'Intellectual'), ('Spiritual', 'Spiritual')], max_length=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_content', models.TextField(max_length=100)),
                ('tip_title', models.CharField(max_length=30)),
                ('tip_ID', models.IntegerField()),
                ('response_for_tag', models.CharField(choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Social', 'Social'), ('Occupational', 'Occupational'), ('Intellectual', 'Intellectual'), ('Spiritual', 'Spiritual')], max_length=10)),
            ],
        ),
    ]
