# Generated by Django 2.1.7 on 2019-02-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_tag',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Social', 'Social'), ('Occupational', 'Occupational'), ('Intellectual', 'Intellectual'), ('Spiritual', 'Spiritual')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tips',
            name='response_for_tag',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Social', 'Social'), ('Occupational', 'Occupational'), ('Intellectual', 'Intellectual'), ('Spiritual', 'Spiritual')], max_length=15),
        ),
    ]
